Traceback (most recent call last):
  File "scripts/qualitative_eval.py", line 123, in <module>
    main(args)
  File "scripts/qualitative_eval.py", line 118, in main
    _args.dataset_name, _args.pred_len, ade, fde))
NameError: name 'ade' is not defined
